# Generated by Django 3.1.2 on 2024-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240522_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
