# Generated by Django 3.1.2 on 2024-05-22 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240522_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='contacto',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='compra',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='compra',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sucursal'),
        ),
    ]
