# Generated by Django 3.1.2 on 2024-05-22 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='contacto',
        ),
    ]
