# Generated by Django 3.1.2 on 2024-05-23 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_compra_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='imagen',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='boleta',
            name='transferencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='boleta',
            name='validacion',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
