# Generated by Django 3.1.2 on 2024-05-27 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240526_1858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoAceptado',
        ),
    ]
